algoritmo "Creuza01"
// Função :Saber a quantidade de velas por no bolo
// Autor : Bruno Neemias
// Data : 29/10/2017
// Seção de Declarações 
var
   Ano_atual, Ano_Nascimento, Idade: Inteiro

inicio
// Seção de Comandos
   escreva("Em que ano nós estamos? ")
   leia(Ano_atual)
   escreva("Em que ano eu nasci? ")
   leia(Ano_Nascimento)
   Idade<- Ano_atual - Ano_Nascimento
   escreva(" Minha idade será: ", Idade)
fimalgoritmo
