algoritmo "Procedimento"
// Função : Somar dois numero atraves do procedimento
// Autor : Bruno Neemias
// Data : 10/02/2018
// Seção de Declarações 
var
   X, Y: INTEIRO
   Procedimento soma(A, B: inteiro)
inicio
      Escreval( "Recebi o valor", A)
      Escreval( "Recebi o valor", B)
      Escreval( "A soma entre  os dois é ", A + B)

Fimprocedimento
inicio
      X <- 5
      Y <- 3
      soma(X, Y )
fimalgoritmo
