algoritmo "Par ou ímpar"
// Disciplina   : [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Função : Ler um numero e dizer se ele é par ou ímpar
// Autor :  Bruno Neemias
// Data : 29/10/2017
// Seção de Declarações
var
N:inteiro
inicio
// Seção de Comandos
escreva("Digite um número: ")
leia(N)
se N%2=0 entao
     escreval("O número é par")
senao
   escreval("O número é impar")
fimse
fimalgoritmo
