algoritmo "parOUímpar"
// Disciplina   : [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Função : Dizer se o número é par ou ímpar
// Autor : Bruno Neemias
// Data : 12/01/2018
// Seção de Declarações
var
num: inteiro
inicio
Escreva("Digite um número (INTEIRO): ")
leia(num)
se (num%2=0) entao
   escreval("O número ",num," é par")
senao
   escreval("O número ",num," é ímpar")
fimse
fimalgoritmo
